# Generated by Django 2.2.13 on 2021-04-24 02:22

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_order_billing_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='coutries',
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='coutry',
            field=django_countries.fields.CountryField(default='China', max_length=2),
            preserve_default=False,
        ),
    ]
