# Generated by Django 2.2.13 on 2021-04-25 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210425_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='coutry',
            new_name='country',
        ),
    ]
